package com.zhimu.news.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zhimu.news.dao.NewsCollect;
import com.zhimu.news.dao.NewsCollectImgUrl;

import com.zhimu.news.dao.NewsCollectDao;
import com.zhimu.news.dao.NewsCollectImgUrlDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsCollectDaoConfig;
    private final DaoConfig newsCollectImgUrlDaoConfig;

    private final NewsCollectDao newsCollectDao;
    private final NewsCollectImgUrlDao newsCollectImgUrlDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsCollectDaoConfig = daoConfigMap.get(NewsCollectDao.class).clone();
        newsCollectDaoConfig.initIdentityScope(type);

        newsCollectImgUrlDaoConfig = daoConfigMap.get(NewsCollectImgUrlDao.class).clone();
        newsCollectImgUrlDaoConfig.initIdentityScope(type);

        newsCollectDao = new NewsCollectDao(newsCollectDaoConfig, this);
        newsCollectImgUrlDao = new NewsCollectImgUrlDao(newsCollectImgUrlDaoConfig, this);

        registerDao(NewsCollect.class, newsCollectDao);
        registerDao(NewsCollectImgUrl.class, newsCollectImgUrlDao);
    }
    
    public void clear() {
        newsCollectDaoConfig.getIdentityScope().clear();
        newsCollectImgUrlDaoConfig.getIdentityScope().clear();
    }

    public NewsCollectDao getNewsCollectDao() {
        return newsCollectDao;
    }

    public NewsCollectImgUrlDao getNewsCollectImgUrlDao() {
        return newsCollectImgUrlDao;
    }

}
