package com.zhimu.news.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEWS_COLLECT".
 */
public class NewsCollect {

    private Long id;
    /** Not-null value. */
    private String title;
    private String source;
    private String desc;
    private String html;
    private String pubDate;
    private String link;
    private Boolean isImgUrl;

    public NewsCollect() {
    }

    public NewsCollect(Long id) {
        this.id = id;
    }

    public NewsCollect(Long id, String title, String source, String desc, String html, String pubDate, String link, Boolean isImgUrl) {
        this.id = id;
        this.title = title;
        this.source = source;
        this.desc = desc;
        this.html = html;
        this.pubDate = pubDate;
        this.link = link;
        this.isImgUrl = isImgUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getHtml() {
        return html;
    }

    public void setHtml(String html) {
        this.html = html;
    }

    public String getPubDate() {
        return pubDate;
    }

    public void setPubDate(String pubDate) {
        this.pubDate = pubDate;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public Boolean getIsImgUrl() {
        return isImgUrl;
    }

    public void setIsImgUrl(Boolean isImgUrl) {
        this.isImgUrl = isImgUrl;
    }

}
