package com.zhimu.news.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEWS_COLLECT_IMG_URL".
 */
public class NewsCollectImgUrl {

    private Long id;
    /** Not-null value. */
    private String title;
    private String imgUrl;

    public NewsCollectImgUrl() {
    }

    public NewsCollectImgUrl(Long id) {
        this.id = id;
    }

    public NewsCollectImgUrl(Long id, String title, String imgUrl) {
        this.id = id;
        this.title = title;
        this.imgUrl = imgUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

}
